name: CI

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # ---------- общий шаг ---------------------------------------------------------
  job-common:
    runs-on: windows-latest
    outputs:
      SHORT_SHA: ${{ steps.expose_sha.outputs.SHORT_SHA }}
    steps:
      - name: expose short commit sha
        id: expose_sha
        shell: pwsh
        run: |
          $short = "${{ github.sha }}".Substring(0,7)
          "SHORT_SHA=$short" | Out-File -FilePath $env:GITHUB_OUTPUT  -Encoding utf8 -Append
          "short_sha=$short" | Out-File -FilePath $env:GITHUB_ENV     -Encoding utf8 -Append

  # ---------- сборка Android ----------------------------------------------------
  build-android:
    needs: job-common
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      SHORT_SHA: ${{ needs.job-common.outputs.SHORT_SHA }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.USERPROFILE }}\.gradle\caches
          key: gradle-${{ runner.os }}-${{ hashFiles('/*.gradle*', '/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: cache gradle wrapper
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.USERPROFILE }}\.gradle\wrapper
          key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: clean outputs directory
        shell: pwsh
        run: |
          if (Test-Path 'app\build\outputs') {
              Remove-Item 'app\build\outputs\*' -Recurse -Force
          }

      # gradlew.bat уже исполняемый, chmod не нужен
      - name: assemble debug artifact
        shell: pwsh
        run: .\gradlew.bat assembleDebug

      - name: upload artifacts to outputs
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk
